"""add password and role status enum for user

Revision ID: 484109d94a21
Revises: 21cb893ff1cd
Create Date: 2026-04-14 09:28:45.118774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484109d94a21'
down_revision: Union[str, Sequence[str], None] = '21cb893ff1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Crée les types enum PostgreSQL d'abord
    userrole = sa.Enum('SUPERADMIN', 'ADMIN', 'SUPERVISOR', 'DRIVER', 'OPERATOR', name='userrole')
    userstatus = sa.Enum('ACTIVE', 'INACTIVE', name='userstatus')
    userrole.create(op.get_bind())
    userstatus.create(op.get_bind())

    op.add_column('fpi_users', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('fpi_users', sa.Column('role', sa.Enum('SUPERADMIN', 'ADMIN', 'SUPERVISOR', 'DRIVER', 'OPERATOR', name='userrole'), server_default='OPERATOR', nullable=False))
    op.add_column('fpi_users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), server_default='ACTIVE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fpi_users', 'status')
    op.drop_column('fpi_users', 'role')
    op.drop_column('fpi_users', 'password')
    # ### end Alembic commands ###
